spring.application.name=PrimerApi
spring.datasource.url=jdbc:mysql://localhost:3306/biblioteca2
spring.datasource.username=root
spring.datasource.password=root
server.servlet.context-path=/micro
spring.jpa.show-sql=true